created form for assigning student
BloomTech-Labs/village-book-builders-fe-b pull request #7
Opened 2021-03-04 21:36 UTC by kasech-isaac

2021-03-09 01:44 UTC, markanator requested changes
Hey Kasi, I saw see there are some empty files in this PR. Can you remove those three files? Other than that, looks good!

2021-03-10 19:18 UTC, markanator requested changes

2021-03-10 19:18 UTC, markanator commented on src/components/pages/Headmaster/Signup.js
> +import MentorandMenteeR from './MentorandMenteeR';
Kasi, what does this file do?

2021-03-11 04:07 UTC, markanator approved these changes, later dismissed

2021-03-16 23:18 UTC, masantea approved these changes, later dismissed

2021-03-17 22:00 UTC, markanator approved these changes, later dismissed

2021-03-23 23:51 UTC, markanator approved these changes

2021-03-23 23:51 UTC, JoseSustaita approved these changes
Nice! We now have a form to assign a student/mentor to a session

2021-03-23 23:51 UTC, merged